# Change these first
owner: kragleh # Your GitHub organization or username, where this repository lives
repo: status.maze.quest # The name of this repository

sites:
  - name: Homepage
    url: https://maze.quest
  - name: Homepage Backend
    url: https://cms.maze.quest
  - name: Minecraft Proxy
    check: "tcp-ping"
    url: play.maze.quest
    port: 25565
    icon: https://www.minecraft.net/etc.clientlibs/minecraft/clientlibs/main/resources/favicon-32x32.png
  - name: Node 1
    url: https://node.kragleh.com:8080
    expectedStatusCodes:
      - 200
      - 401

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.maze.quest
  # baseUrl: /your-repo-name
  logoUrl: https://maze.quest/favicon.ico
  name: Maze Quest
  theme: night
  introTitle: ""
  introMessage: Welcome to our status page, where we provide real-time updates on the performance and uptime of our services.
  navbar:
    - title: Status
      href: /
    - title: Home
      href: https://maze.quest

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
